package com.example.thoughts_cleaning.common

/**
 * Created by SeoKang on 2021-05-21.
 */
object Constants {
    const val USER_AGENT = "xouchcare android"
    const val BASE_URL = "http://thoughtclean.dnx.kr:8910"
    const val BASE_URL_TEST = "http://thoughtclean.dnx.kr:8910"
    const val PLAY_STORE_URL = "https://play.google.com/store/apps/details"
    const val STORE_URL = "$PLAY_STORE_URL?id="

    /**
     * KEY
     */
    const val KEY_ACQUIRE_POINT = "acquire_point"
    const val KEY_ACT_TYPE = "act_type"
    const val KEY_ACTIONS = "actions"
    const val KEY_ADDITIONAL_FLAG = "additional_flag"
    const val KEY_ADDRESS = "address"
    const val KEY_AGE = "age"
    const val KEY_ALARM_ENABLE = "alarm_enable"
    const val KEY_ALARM_TYPE = "alarm_type"
    const val KEY_APP_DEVICE_ID = "app_device_id"
    const val KEY_APP_LANG = "app_lang"
    const val KEY_APP_VERSION = "app_version"
    const val KEY_AT = "at"

    const val KEY_BATTERY_LEVEL = "battery_level"
    const val KEY_BG_IMAGE_URL = "bg_image_url"
    const val KEY_BG_TEXT = "bg_text"
    const val KEY_BLE_STATUS = "ble_status"
    const val KEY_BLE_TIME = "ble_time"
    const val KEY_BIRTHDAY = "birthday"
    const val KEY_BIRTHDAY_TYPE = "birthday_type"
    const val KEY_BODY = "body"
    const val KEY_BROADCAST_END_MESSAGE = "broadcast_end_message"
    const val KEY_BROADCAST_ID = "broadcast_id"
    const val KEY_BROADCAST_LIST = "broadcast_list"
    const val KEY_BROADCAST_ON_AIR_ID = "broadcast_on_air_id"
    const val KEY_BROADCAST_NEXT_AT = "broadcast_next_at"
    const val KEY_BROADCAST_TITLE = "broadcast_title"
    const val KEY_BUY_LIST = "buy_list"

    const val KEY_CANCEL_REASON = "cancel_reason"
    const val KEY_CAMPUS_NAME = "campus_name"
    const val KEY_CAN_ADD_CONTACT = "can_add_contact"
    const val KEY_CAN_ADD_TAG = "can_add_tag"
    const val KEY_CAN_UPGRADE = "can_upgrade"
    const val KEY_CATEGORIES = "categories"
    const val KEY_CATEGORY = "category"
    const val KEY_CATEGORY_DESC = "category_desc"
    const val KEY_CATEGORY_ID = "category_id"
    const val KEY_CATEGORY1_ID = "category1_id"
    const val KEY_CATEGORY2_ID = "category2_id"
    const val KEY_CATEGORY3_ID = "category3_id"
    const val KEY_CATEGORY_NAME = "category_name"
    const val KEY_CB_VIA_TYPE = "cb_via_type"
    const val KEY_CENTER_LATITUDE = "center_latitude"
    const val KEY_CENTER_LONGITUDE = "center_longitude"
    const val KEY_CERT_NO = "cert_no"
    const val KEY_CHANNELS = "channels"
    const val KEY_CHANNEL_ID = "channel_id"
    const val KEY_CHANNEL_NAME = "channel_name"
    const val KEY_CHANNEL_NO = "channel_no"
    const val KEY_CLIENT_AT = "client_at"
    const val KEY_CLIENT_TIME = "client_time"
    const val KEY_COLLEGE_LIST = "college_list"
    const val KEY_COMMAND_WAITING_DURATION = "command_waiting_duration"
    const val KEY_CONTACTS = "contacts"
    const val KEY_CONTENT = "__content__"
    const val KEY_CONTENT_LIST = "content_list"
    const val KEY_CONTENT_ID = "content_id"
    const val KEY_CONTENT_URL = "content_url"
    const val KEY_COUNTRY_NO = "country_no"
    const val KEY_CREATE_TIME = "create_time"

    const val KEY_DAIlY = "daily"
    const val KEY_DATA_REGISTER_1 = "data_register_1"
    const val KEY_DATA_REGISTER_2 = "data_register_2"
    const val KEY_DATA_REGISTER_3 = "data_register_3"
    const val KEY_DATA_REGISTER_4 = "data_register_4"
    const val KEY_DATA_CONTACT = "data_contact"
    const val KEY_DATA_FIND = "data_find"
    const val KEY_DATA_ID = "data_id"
    const val KEY_DATA_NEW_TAG = "data_new_tag"
    const val KEY_DATA_PRIVACY_TYPE = "data_privacy_type"
    const val KEY_DATA_PRIVACY_URL = "data_privacy_url"
    const val KEY_DATA_VOLUME = "data_volume"
    const val KEY_DATE = "date"
    const val KEY_DAYS = "days"
    const val KEY_DESC_QUANTITY = "desc_quantity"
    const val KEY_DESC_VOLUME = "desc_volume"
    const val KEY_DESCRIPTION ="description"
    const val KEY_DEVICE_ID = "device_id"
    const val KEY_DEVICE_NAME = "device_name"
    const val KEY_DEVICE_TYPE = "device_type"
    const val KEY_DEVICES = "devices"
    const val KEY_DFU_URL = "dfu_url"
    const val KEY_DURATION = "duration"
    const val KEY_DUST = "dust"

    const val KEY_E_DATE = "e_date"
    const val KEY_ENABLE = "enable"
    const val KEY_ENABLE_PUSH_LIST = "enable_push_list"
    const val KEY_END_DATE = "end_date"
    const val KEY_END_TIME = "end_time"
    const val KEY_ERROR_CODE = "error_code"
    const val KEY_ERROR_MESSAGE = "error_message"
    const val KEY_EVENT_END = "event_end"
    const val KEY_EVENT_ID = "event_id"
    const val KEY_EVENT_LIST ="event_list"
    const val KEY_EVENT_PAUSE = "event_pause"
    const val KEY_EVENT_TYPE = "event_type"
    const val KEY_EVENT_PUSH = "event_push"
    const val KEY_EVENT_NEW_TAG = "event_new_tag"
    const val KEY_EXPIRE_DATE = "expire_date"

    const val KEY_FAMILY_LIST = "family_list"
    const val KEY_FAMILY_USER_ID = "family_user_id"
    const val KEY_FAVORITE_ORDER = "favorite_order"
    const val KEY_FCM_REG_ID = "fcm_reg_id"
    const val KEY_FOLLOW_LIST = "follow_list"
    const val KEY_FOLLOW_NAME = "follow_name"
    const val KEY_FOLLOW_USER_ID = "follow_user_id"
    const val KEY_FOLLOWER_COUNT = "follower_count"

    const val KEY_GIVER_NAME = "giver_name"
    const val KEY_GPS_ACCURACY = "gps_accuracy"
    const val KEY_GPS_ACTIVE_STATUS = "gps_active_status"
    const val KEY_PERIOD_COLLECT_DURATION = "period_collect_duration"
    const val KEY_GPS_AT = "gps_at"
    const val KEY_GRADE = "grade"
    const val KEY_GRADE_HEALTH = "grade_health"
    const val KEY_GRADE_RECOGNIZE = "grade_recognize"
    const val KEY_GRADE_REGULAR = "grade_regular"
    const val KEY_GUARDIAN_LIST = "guardian_list"
    const val KEY_GUARDIANS = "guardians"

    const val KEY_HAVE_DEVICE = "have_device"
    const val KEY_HAVE_LIGHT_SENSOR = "have_light_sensor"
    const val KEY_HAVE_PROXIMITY_SENSOR = "have_proximity_sensor"
    const val KEY_HAVE_STEP_SENSOR = "have_step_sensor"
    const val KEY_HEIGHT = "height"
    const val KEY_HOME_LATITUDE = "home_latitude"
    const val KEY_HOME_LONGITUDE = "home_longitude"
    const val KEY_HOME_ADDRESS_TEXT1 = "home_address_text1"
    const val KEY_HOME_ADDRESS_TEXT2 = "home_address_text2"
    const val KEY_HS_POINT_LIST = "hs_point_list"

    const val KEY_ID = "id"
    const val KEY_IMAGE_LIST = "image_list"
    const val KEY_IMAGE_URL = "image_url"
    const val KEY_INCLUDE_ViDEO = "include_video"
    const val KEY_IS_CHARGE = "is_charge"
    const val KEY_IS_DRAWING = "is_drawing"
    const val KEY_IS_EXIST_USER = "is_exist_user"
    const val KEY_IS_OLD_APP = "is_old_app"
    const val KEY_IS_NEW_USER = "is_new_user"
    const val KEY_IS_NOTIFICATION_ON = "is_notification_on"
    const val KEY_IS_PHONE_SCAN_ON = "is_phone_scan_on"
    const val KEY_IS_RESERVE = "is_reserve"
    const val KEY_IS_TRADE = "is_trade"

    const val KEY_LANG = "lang"
    const val KEY_LAST_APP_VERSION = "last_app_version"
    const val KEY_LAST_ID = "last_id"
    const val KEY_LAST_INFO = "last_info"
    const val KEY_LAST_LATITUDE = "last_latitude"
    const val KEY_LAST_LOCATION_TIME = "last_location_time"
    const val KEY_LAST_LONGITUDE = "last_longitude"
    const val KEY_LAST_VERSION = "last_version"
    const val KEY_LATITUDE = "latitude"
    const val KEY_LIKE_COUNT = "like_count"
    const val KEY_LIST_COUNT = "list_count"
    const val KEY_LIVE = "__live__"
    const val KEY_LIVE_CATEGORY = "live_category"
    const val KEY_LIVE_DATE = "live_date"
    const val KEY_LIVE_ID = "live_id"
    const val KEY_LIVE_LIST = "live_list"
    const val KEY_LIVE_TITLE = "live_title"
    const val KEY_LIVE_WATCHING = "live_watching"
    const val KEY_LOCATION = "location"
    const val KEY_LOCATIONS = "locations"
    const val KEY_LOCATION_TIME = "location_time"
    const val KEY_LOGIN_ID = "login_id"
    const val KEY_PAID_SUBSCRIBE_ID = "subscribe_info"
    const val KEY_PAID_SUBSCRIBE_ALERT_TEXT = "subscribe_alert_text"
    const val KEY_LOGIN_STATUS = "login_status"
    const val KEY_LONGITUDE = "longitude"

    const val KEY_OK = "OK"
    const val KEY_ORDER_COUNT = "order_count"
    const val KEY_ORDER_DATE = "order_date"
    const val KEY_OS_VERSION = "os_version"
    const val  KEY_OWNER_ID= "owner_id"
    const val  KEY_ROOM_ID= "room_id"
    const val KEY_GUARDIAN_ID = "guardian_id"
    const val KEY_OWNER_LIST = "owner_list"
    const val KEY_OWNER_PHONE_NO = "owner_phone_no"

    const val KEY_MAIN_TYPE = "main_type"
    const val KEY_MASIL_LIST = "masil_list"
    const val KEY_MAJOR = "major"
    const val KEY_MAX_NTH = "max_nth"
    const val KEY_MAX_STEP = "max_step"
    const val KEY_MEMO = "memo"
    const val KEY_MESSAGE = "message"
    const val KEY_MESSAGE_LIST = "message_list"
    const val KEY_MODEL_NAME = "model_name"
    const val KEY_MOTION_ON_DURATION = "motion_on_duration"
    const val KEY_MOTION_PERIOD = "motion_period"
    const val KEY_MOTION_UPLOAD_PERIOD = "motion_upload_period"
    const val KEY_MOVEMENTS = "movements"
    const val KEY_MUST_STEP_COUNT = "must_step_count"

    const val KEY_NAME = "name"
    const val KEY_NANUM = "nanum"
    const val KEY_NANUM_TYPE = "nanum_type"
    const val KEY_NEED_GPS = "need_gps"
    const val KEY_NEED_HOME_GPS = "need_home_gps"
    const val KEY_NEW_MAIN_TYPE = "new_main_type"
    const val KEY_NEW_PASSWORD = "new_password"
    const val KEY_NEXT_CONTENT_ID = "next_content_id"
    const val KEY_NEXT_CONTENT_THUMBNAIL_URL = "next_content_thumbnail_url"
    const val KEY_NEXT_WAITING_DURATION = "next_waiting_duration"
    const val KEY_NOTICE_LIST = "notice_list"
    const val KEY_NTH = "nth"

    const val KEY_P_ID = "__pid"
    const val KEY_P_TAG_BATTERY_STATUS = "p_tag_battery_status"
    const val KEY_P_TAG_DISTANCE = "p_tag_distance"
    const val KEY_P_TAG_ID = "p_tag_id"
    const val KEY_P_TAG_CHANGE_STATUS = "p_tag_change_status"
    const val KEY_P_TAG_GROUP = "p_tag_group"
    const val KEY_PASSWORD = "password"
    const val KEY_PAYLOAD = "payload"
    const val KEY_PAYLOADS = "payloads"
    const val KEY_PAYLOAD_LIST = "payload_list"
    const val KEY_PERIOD_LIST = "period_list"
    const val KEY_PERIOD_PUSH_REQUEST_LOCATION = "period_push_request_location"
    const val KEY_PHONE_BATTERY_LEVEL = "phone_battery_level"
    const val KEY_PHONE_BLE_STATUS = "phone_ble_status"
    const val KEY_PHONE_BEACON_SCAN_STATUS = "phone_beacon_scan_status"
    const val KEY_PHONE_DNX_STEP = "phone_dnx_step"
    const val KEY_PHONE_IS_CHARGE = "phone_is_charge"
    const val KEY_PHONE_IS_CHARGE_CHANGE_STATUS = "phone_is_charge_change_status"
    const val KEY_PHONE_NO = "phone_no"
    const val KEY_PHONE_SCREEN_CHANGE_STATUS = "phone_screen_change_status"
    const val KEY_PHONE_SCREEN_ON_STATUS = "phone_screen_on_status"
    const val KEY_PHONE_STEP = "phone_step"
    const val KEY_PHONE_TOTAL_STEP = "phone_total_step"
    const val KEY_PLAY_TIME = "play_time"
    const val KEY_POINT = "point"
    const val KEY_POINT_LIST = "point_list"
    const val KEY_POSTURE = "posture"
    const val KEY_POST_SLEEP_DURATION = "post_sleep_duration"
    const val KEY_PREV_SKIP = "prev_skip"
    const val KEY_PRICE = "price"
    const val KEY_PRICE_UNIT = "price_unit"
    const val KEY_PRIVACY = "privacy"
    const val KEY_PRODUCT_ID = "product_id"
    const val KEY_PRODUCT_LIST = "product_list"
    const val KEY_PROGRAM_NAME = "program_name"
    const val KEY_PUSHES = "pushes"
    const val KEY_PUSH_ID = "push_id"

    const val KEY_RECOMMEND_LIST = "recommend_list"
    const val KEY_R1_GRADE = "r1_grade"
    const val KEY_R1_SCORE = "r1_score"
    const val KEY_R1_TEXT = "r1_text"
    const val KEY_R2_GRADE = "r2_grade"
    const val KEY_R2_SCORE = "r2_score"
    const val KEY_R2_TEXT = "r2_text"
    const val KEY_R3_GRADE = "r3_grade"
    const val KEY_R3_SCORE = "r3_score"
    const val KEY_R3_TEXT = "r3_text"

    const val KEY_REASON = "reason"
    const val KEY_RECORD_CODEC = "record_codec"
    const val KEY_RECORD_STYLE = "record_style"
    const val KEY_RECORD_DURATION = "record_duration"
    const val KEY_REMAIN_DAYS = "remain_days"
    const val KEY_REQUEST_ID = "request_id"
    const val KEY_RESULT = "result"
    const val KEY_RETRY_STATUS = "retry_status"

    const val KEY_BEFORE_VTS_MESSAGE = "before_vts_message"
    const val KEY_TITLE_VTS_MESSAGE = "title_vts_message"
    const val KEY_QUIZ_ANSWER_CHECK = "quiz_answer_check"
    const val KEY_QUIZ_USER_MESSAGE = "user_message"


    const val KEY_S_DATE = "s_date"
    const val KEY_SAMPLE_RATE = "sample_rate"
    const val KEY_SCORE_HEALTH = "score_health"
    const val KEY_SCORE_RECOGNIZE = "score_recognize"
    const val KEY_SCORE_REGULAR = "score_regular"
    const val KEY_SCREEN_ID = "screen_id"
    const val KEY_SENDER = "sender"
    const val KEY_SEQ = "seq"
    const val KEY_SERVICE = "service"
    const val KEY_SESSION_KEY = "session_key"
    const val KEY_SEX = "sex"
    const val KEY_SHORT_NAME = "short_name"
    const val KEY_SS_LIGHT = "ss_light"
    const val KEY_SS_PROXIMITY = "ss_proximity"
    const val KEY_START_AGO = "start_ago"
    const val KEY_START_DATE = "start_date"
    const val KEY_START_TIME = "start_time"
    const val KEY_STATUS = "status"
    const val KEY_STEP = "step"
    const val KEY_STEP_DATE = "step_date"
    const val KEY_STEP_LENGTH = "step_length"
    const val KEY_STEP_POINT_BOX = "step_point_box"
    const val KEY_STEP_SPEED = "step_speed"
    const val KEY_STOCK = "stock"
    const val KEY_STT = "stt"
    const val KEY_SUBSCRIBE_GRADE = "subscribe_grade"
    const val KEY_SUBSCRIBE_START_DATE = "subscribe_start_date"
    const val KEY_SUBSCRIBE_END_DATE = "subscribe_end_date"
    const val KEY_SUNI_WAIT_DURATION = "suni_wait_duration"

    const val KEY_TAGS = "tags"
    const val KEY_TAG_BATTERY_STATUS = "tag_battery_status"
    const val KEY_TAG_GROUP = "tag_group"
    const val KEY_TAG_ID = "tag_id"
    const val KEY_TAG_NAME = "tag_name"
    const val KEY_TAG_LIST = "tag_list"
    const val KEY_TEMPERATURE = "temperature"
    const val KEY_TEXT = "text"
    const val KEY_TEXT_COLOR = "text_color"
    const val KEY_THUMBNAIL_URL = "thumbnail_url"
    const val KEY_TIME = "time"
    const val KEY_TIMEZONE = "timezone"
    const val KEY_TITLE = "title"
    const val KEY_TITLE1 = "title1"
    const val KEY_TITLE2 = "title2"
    const val KEY_TOTAL_COUNT = "total_count"
    const val KEY_TOTAL_POINT = "total_point"
    const val KEY_TOTAL_STEP = "total_step"
    const val KEY_TOUCH_TIME = "touch_time"
    const val KEY_TRACE_DATE = "trace_date"
    const val KEY_TRACES = "traces"
    const val KEY_TTS_LANG = "tts_lang"
    const val KEY_TYPE = "type"

    const val KEY_URL = "url"
    const val KEY_USER_NAME = "user_name"
    const val KEY_USER_ID = "user_id"
    const val KEY_USER_TYPE = "user_type"
    const val KEY_GUARDIAN_USER_ID = "guardian_user_id"

    const val KEY_VERSION = "version"
    const val KEY_VIEW_COUNT = "view_count"
    const val KEY_VOICE_AT = "voice_at"
    const val KEY_VOICE_ID = "voice_id"
    const val KEY_VOICE_LIST = "voice_list"
    const val KEY_VOICE_RECORD_DURATION = "voice_record_duration"
    const val KEY_VOICE_URL = "voice_url"
    const val KEY_VOLUME = "volume"
    const val KEY_VTS_ID = "vts_id"

    const val KEY_WEATHER = "weather"
    const val KEY_WEEKLY = "weekly"
    const val KEY_WINNER_LIST = "winner_list"

    const val KEY_VTS = "__vts__"

//    const val KEY_CATEGORY1_ID = "category1_id"
    const val KEY_CATEGORY1_NAME = "category1_name"
//    const val KEY_TITLE = "image_url"


    /**
     * ERROR TYPE
     */
    const val ERROR_CODE_NEED_APP_UPDATE = "NEED_APP_UPDATE"
    const val ERROR_CODE_NO_VTS = "NO_VTS"
    const val ERROR_CODE_XCER_105 = "XCER105"
    const val ERROR_CODE_XCER_109 = "XCER109"

    const val ERROR_CODE_SWER_004 = "SWER004"
    const val ERROR_CODE_SWER_005 = "SWER005"
    const val ERROR_CODE_SWER_009 = "SWER009"
    const val ERROR_CODE_INVALID_LANGUAGE = "INVALID_LANG"
    const val ERROR_CODE_SHOP_ALREADY_ORDER = "SHOP_ALREADY_ORDER"
    const val ERROR_CODE_MUST_LOGIN_AS_OWNER = "MUST_LOGIN_AS_OWNER"
    const val ERROR_CODE_EVENT_NOT_END = "EVENT_NOT_END"
    const val ERROR_CODE_EVENT_IS_TOO_OLD = "EVENT_IS_TOO_OLD"
    const val ERROR_CODE_FOLLOW_EXCEED_SEARCH = "FOLLOW_EXCEED_SEARCH"
    const val ERROR_CODE_FOLLOW_ALREADY = "FOLLOW_ALREADY"
    const val ERROR_CODE_FAMILY_ALREADY = "FAMILY_ALREADY"
    const val ERROR_CODE_NANUM_ALREADY_GIVE_REQUEST = "NANUM_ALREADY_GIVE_REQUEST"
    const val ERROR_CODE_NANUM_ALREADY_BUY_REQUEST = "NANUM_ALREADY_BUY_REQUEST"
    const val ERROR_CODE_NO_ON_AIR_BROADCAST = "NO_ON_AIR_BROADCAST"

    const val ERROR_CODE_XC_EMERGENCY_01 = "XC_EMERGENCY_01"
    const val ERROR_CODE_XC_EMERGENCY_02 = "XC_EMERGENCY_02"

    const val ERROR_CODE_RECORD_INVALID = "RECORD_INVALID"
    const val ERROR_CODE_AUDIO_RECORD_NOT_INITIALIZE = "AUDIO_RECORD_NOT_INITIALIZE"
    const val ERROR_CODE_MEDIA_RECORD_EXCEPTION = "MEDIA_RECORD_EXCEPTION"
    const val ERROR_CODE_MEDIA_PLAYER_EXCEPTION = "MEDIA_PLAYER_EXCEPTION"

    const val CALLBACK_CODE_WEARER_PERMMISION = 101
    const val CALLBACK_CODE_CONTACT_INFO = 102
    const val CALLBACK_CODE_BLUETOOTH_REQUEST = 1592
    const val CALLBACK_CODE_LOCATION_REQUEST = 1593

    const val INSTANCE_START_SERVICE = "start_service"
    const val INSTANCE_STOP_SERVICE = "stop_service"

    const val GPS_RESTART_SERVICE = "gps_restart_service" //20240614 add

    /**
     * PUSH CODE
     */
    const val PUSH_EVENT_ALERT_MESSAGE = "ALERT_MESSAGE"
    const val PUSH_EVENT_CONFIRM_MESSAGE = "CONFIRM_MESSAGE"
    const val PUSH_EVENT_AUTO_LOGOUT = "AUTO_LOGOUT"

    const val PUSH_EVENT_PERIOD_PHONE_GPS = "PERIOD_PHONE_GPS"

    const val PUSH_EVENT_SERVICE_DISABLE_LOCK_SCREEN = "SERVICE_DISABLE_LOCK_SCREEN"
    const val PUSH_EVENT_TTS_MESSAGE = "TTS_MESSAGE"
    const val PUSH_EVENT_TTS_MESSAGE_ALL = "TTS_MESSAGE_ALL"
    const val PUSH_EVENT_TTS_VOICE_URL = "VOICE_URL"
    const val PUSH_EVENT_TTS_MESSAGE_TITLE = "TTS_MESSAGE_TITLE"
    const val PUSH_EVENT_LAZY_TTS = "XC_LAZY_VTS"
    const val PUSH_EVENT_MOTION_REMOTE_ON = "XC_REMOTE_MOTION_ON"
    const val PUSH_EVENT_MOTION_REMOTE_OFF = "XC_REMOTE_MOTION_OFF"
    const val PUSH_EVENT_MOTION_ON = "XC_MOTION_ON"
    const val PUSH_EVENT_MESSAGE = "MESSAGE"
    const val PUSH_EVENT_KILL_SERVICE = "KILL_SERVICE"
    const val PUSH_EVENT_CHANGE_VIA_TYPE = "XC_CB_VIA_TYPE"
    const val PUSH_EVENT_BROADCAST_CLEAR = "BROADCAST_CLEAR"
    const val PUSH_EVENT_BROADCAST_START = "BROADCAST_START"
    const val PUSH_EVENT_BROADCAST_END = "BROADCAST_END"
    const val PUSH_EVENT_BROADCAST_VTS = "BROADCAST_VTS"
    const val PUSH_EVENT_BROADCAST_CLEAR_BG_TEXT = "BROADCAST_CLEAR_BG_TEXT"

    const val EVENT_STOP_BACKGROUND_VTS = "STOP_BACKGROUND_VTS"
    const val EVENT_LOCAL_NEW_TAG = "NEW_TAG"
    const val EVENT_LOCAL_SHOW_WARNING = "SHOW_WARNING"

    const val LANGUAGE_CODE_SPAIN = "es"

    const val NCALL_REMOCON_SERVICE = "6e400001-b5a3-f393-e0a9-e50e24dcca9e"
    const val NCALL_REMOCON_SEND_DATA_CHAR = "6e400002-b5a3-f393-e0a9-e50e24dcca9e"
    const val NCALL_REMOCON_KEY_NOTI_CHAR = "6e400003-b5a3-f393-e0a9-e50e24dcca9e"
    const val NCALL_REMOCON_SEND_PATTERN_CHAR = "6e407aa4-b5a3-f393-e0a9-e50e24dcca9e"
    const val CCCD = "00002902-0000-1000-8000-00805f9b34fb"

    /**
     * VTS CANCEL REASON
     */
    const val VTS_CANCEL_MASIL = "masil mode"
    const val VTS_CANCEL_SILENT = "manner mode"
    const val VTS_CANCEL_CALL = "phone is busy"
    const val VTS_CANCEL_PROGRAM = "program playing"


    const val PUSH_EVENT_START_EMERGENCY = "START_EMERGENCY"
    const val PUSH_EVENT_RANDOM_CALL_SEND_OTHER_OWNER = "RANDOM_CALL_SEND_OTHER_OWNER"
    const val PUSH_EVENT_VIDEO_CHATTING_SEND_OTHER_OWNER = "VIDEO_CHATTING_SEND_OTHER_OWNER"
    const val PUSH_EVENT_OWNER_ACTION_STATE_PUSH = "OWNER_ACTION_STATE_PUSH"

    const val PUSH_EVENT_OWNER_ACTION_AWAKE_STATE = "OWNER_ACTION_AWAKE_STATE"
    const val PUSH_EVENT_OWNER_ACTION_COMEIN_STATE_FIRST = "OWNER_ACTION_COMEIN_STATE_FIRST"
    const val PUSH_EVENT_OWNER_ACTION_COMEIN_STATE_SECOND = "OWNER_ACTION_COMEIN_STATE_SECOND"

    const val KEY_RANDOM_CALL_CATEGOREY = "category"
    const val KEY_VIDEO_CHATTING_IMG_URL = "img_url"
    const val KEY_SUNI_CODE = "suni_code"


    const val KEY_FULL_SEND_MESSAGE = "full_send_message"
}